# Generated by Django 5.0.14 on 2026-02-28 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContributionMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_commits", models.IntegerField(default=0)),
                ("pr_opened", models.IntegerField(default=0)),
                ("pr_merged", models.IntegerField(default=0)),
                ("issues_opened", models.IntegerField(default=0)),
                ("issues_closed", models.IntegerField(default=0)),
                ("external_contributions", models.IntegerField(default=0)),
                ("active_days", models.IntegerField(default=0)),
                ("streak_max", models.IntegerField(default=0)),
                ("last_fetched", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contribution_metrics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Contribution Metrics",
            },
        ),
        migrations.CreateModel(
            name="Repository",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("full_name", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "primary_language",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("stars", models.IntegerField(default=0)),
                ("forks", models.IntegerField(default=0)),
                ("is_fork", models.BooleanField(default=False)),
                ("has_ci", models.BooleanField(default=False)),
                ("has_tests", models.BooleanField(default=False)),
                ("has_docker", models.BooleanField(default=False)),
                ("has_lint", models.BooleanField(default=False)),
                ("has_types", models.BooleanField(default=False)),
                ("size_kb", models.IntegerField(default=0)),
                ("open_issues_count", models.IntegerField(default=0)),
                ("repo_created_at", models.DateTimeField(blank=True, null=True)),
                ("repo_updated_at", models.DateTimeField(blank=True, null=True)),
                ("analyzed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repositories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-stars"],
                "unique_together": {("user", "full_name")},
            },
        ),
    ]
