# Generated by Django 5.0.14 on 2026-03-01 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("github", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RepositoryAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary", models.TextField()),
                ("strengths", models.JSONField(default=list)),
                ("weaknesses", models.JSONField(default=list)),
                ("suggestions", models.JSONField(default=list)),
                ("architecture_score", models.IntegerField(default=0)),
                ("audited_at", models.DateTimeField(auto_now_add=True)),
                (
                    "repository",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit",
                        to="github.repository",
                    ),
                ),
            ],
        ),
    ]
