# Generated by Django 5.0.14 on 2026-03-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("github", "0002_repositoryaudit"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="repository",
            index=models.Index(fields=["user", "-stars"], name="repo_user_stars_idx"),
        ),
        migrations.AddIndex(
            model_name="repository",
            index=models.Index(fields=["user", "repo_updated_at"], name="repo_user_updated_idx"),
        ),
        migrations.AddIndex(
            model_name="repository",
            index=models.Index(fields=["user", "analyzed_at"], name="repo_user_analyzed_idx"),
        ),
    ]
