# Generated by Django 5.0.14 on 2026-05-11 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0003_add_repository_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PinnedRepo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinned_at', models.DateTimeField(auto_now=True)),
                ('click_count', models.IntegerField(default=0)),
                ('weekly_clicks', models.IntegerField(default=0)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_by', to='github.repository')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_repos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pinned_at'],
                'unique_together': {('user', 'repository')},
            },
        ),
        migrations.CreateModel(
            name='RepoClickEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=64)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('pinned_repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_events', to='github.pinnedrepo')),
            ],
            options={
                'indexes': [models.Index(fields=['pinned_repo', '-clicked_at'], name='click_pinned_created_idx')],
                'unique_together': {('pinned_repo', 'session_id')},
            },
        ),
    ]
