# Generated by Django 5.0.14 on 2026-03-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recs", "0002_techrecommendation"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(fields=["user", "is_resolved"], name="recs_user_res_idx"),
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(fields=["user", "-created_at"], name="recs_user_created_idx"),
        ),
        migrations.AddIndex(
            model_name="techrecommendation",
            index=models.Index(fields=["user", "is_dismissed"], name="tech_user_dismissed_idx"),
        ),
        migrations.AddIndex(
            model_name="techrecommendation",
            index=models.Index(fields=["user", "-created_at"], name="tech_user_created_idx"),
        ),
    ]
