# Generated by Django 5.0.14 on 2026-02-28 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScoringConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("weight_engineering", models.FloatField(default=0.3)),
                ("weight_discipline", models.FloatField(default=0.2)),
                ("weight_collaboration", models.FloatField(default=0.2)),
                ("weight_consistency", models.FloatField(default=0.2)),
                ("weight_oss", models.FloatField(default=0.1)),
            ],
            options={
                "verbose_name": "Scoring Configuration",
                "verbose_name_plural": "Scoring Configuration",
            },
        ),
        migrations.CreateModel(
            name="ScoreBreakdown",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("engineering_depth", models.FloatField(default=0.0)),
                ("collaboration", models.FloatField(default=0.0)),
                ("discipline", models.FloatField(default=0.0)),
                ("consistency", models.FloatField(default=0.0)),
                ("oss_impact", models.FloatField(default=0.0)),
                ("last_calculated", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score_breakdown",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScoreHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("score", models.FloatField()),
                ("breakdown_snapshot", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Score History",
                "ordering": ["-created_at"],
            },
        ),
    ]
