# Generated by Django 5.0.14 on 2026-03-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scoring", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="scorehistory",
            index=models.Index(fields=["user", "-created_at"], name="score_user_created_idx"),
        ),
    ]
