# Generated by Django 5.0.14 on 2026-02-28 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeveloperProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "github_username",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("avatar_url", models.URLField(blank=True, default="", max_length=500)),
                ("github_token_encrypted", models.TextField(blank=True, default="")),
                ("bio", models.TextField(blank=True, default="")),
                ("dev_score", models.FloatField(default=0.0)),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("starter", "Starter"),
                            ("rising", "Rising"),
                            ("established", "Established"),
                            ("architect", "Architect"),
                            ("apex", "Apex"),
                        ],
                        default="starter",
                        max_length=20,
                    ),
                ),
                (
                    "analysis_status",
                    models.CharField(
                        choices=[
                            ("idle", "Idle"),
                            ("pending", "Pending"),
                            ("analyzing", "Analyzing"),
                            ("complete", "Complete"),
                            ("failed", "Failed"),
                        ],
                        default="idle",
                        max_length=20,
                    ),
                ),
                ("last_analyzed", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-dev_score"],
            },
        ),
    ]
