# Generated by Django 5.0.14 on 2026-03-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_create_default_admin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="developerprofile",
            name="analysis_status",
            field=models.CharField(
                choices=[
                    ("idle", "Idle"),
                    ("pending", "Pending"),
                    ("analyzing", "Analyzing"),
                    ("complete", "Complete"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="idle",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="developerprofile",
            name="dev_score",
            field=models.FloatField(db_index=True, default=0.0),
        ),
    ]
